package com.example.rostislav.pdfreader.model.database.room.utils

import com.example.rostislav.pdfreader.model.database.room.FileDataRoom
import com.example.rostislav.pdfreader.utils.NamesOfFiles
import com.example.rostislav.pdfreader.utils.StringUtils.emptyString
import com.example.rostislav.pdfreader.utils.StringUtils.getNameFromString

object DatabaseCreator {
    val fileList = mutableListOf(
        FileDataRoom(
            NamesOfFiles.FILE_NAME_1,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_1),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_2,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_2),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_3,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_3),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_4,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_4),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_5,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_5),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_6,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_6),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_7,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_7),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_8,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_8),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_9,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_9),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_10,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_10),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_11,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_11),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_12,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_12),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_13,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_13),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_14,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_14),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_15,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_15),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_16,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_16),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_17,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_17),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_18,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_18),
            emptyString()
        ),
        FileDataRoom(
            NamesOfFiles.FILE_NAME_19,
            emptyString(),
            getNameFromString(NamesOfFiles.FILE_NAME_19),
            emptyString()
        )
    )
}